name: CI Front-end-prof

on:
  push:
    branches:
      - 'main'
    paths:
      - 'front-end/**'
  pull_request:
    paths:
      - 'front-end/**'
  workflow_call:
  workflow_dispatch:
  
jobs:
  teste:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up NODE
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Instalação de dependencias
        working-directory: front-and/
      - name: Compilação / Test / 
        working-directory: front-end/
        run: npm test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
  package:
    needs: teste
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up NODE
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Instalação de dependencias
        working-directory: front-and/
        run: npm clean install
      - name: build
        working-directory: front-end/
        run: npm run build --prod
      - name: Cache App
        uses: actions/cache@v3
        with:
          path: front-end/dist/
          key: build-${{github.sha}}
  
      
